import React from 'react';
import { Link } from 'react-router-dom';
import ImageUpload from '../components/ImageUpload';
import PlantCard from '../components/PlantCard';
import { PlantDetails, Reminder } from '../types';
import { TreePine, Sparkles } from 'lucide-react';

interface Props {
  currentPlant: PlantDetails | null;
  isLoading: boolean;
  history: PlantDetails[];
  lastImage: string | null;
  onIdentify: (base64: string) => Promise<void> | void;
  setCurrentPlant: (p: PlantDetails | null) => void;
  setLastImage: (s: string | null) => void;
  onSetReminder: (type: 'water' | 'fertilizer', interval: number) => void;
  reminders: Reminder[];
}

const Home: React.FC<Props> = ({ currentPlant, isLoading, history, lastImage, onIdentify, setCurrentPlant, setLastImage, onSetReminder, reminders }) => {
  return (
    <div className="space-y-20">
      {!currentPlant && !isLoading && (
        <section className="text-center space-y-6 animate-in fade-in slide-in-from-top-4 duration-1000">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-emerald-50 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 rounded-full text-[10px] font-black uppercase tracking-[0.2em] shadow-sm mb-4 border border-emerald-100 dark:border-emerald-800/50">
            <Sparkles size={12} />
            Next-Gen Botany
          </div>
          <h1 className="text-5xl sm:text-7xl font-serif font-bold text-stone-900 dark:text-stone-100 leading-[1.1]">Nurture Your Nature</h1>
          <p className="text-stone-500 dark:text-stone-400 text-xl max-w-xl mx-auto font-medium leading-relaxed">
            Scan any plant for expert identity and care schedules tailored to your home environment.
          </p>
        </section>
      )}

      {!currentPlant && (
        <ImageUpload onImageCaptured={onIdentify} isLoading={isLoading} />
      )}

      {currentPlant && (
        <div className="space-y-8">
          <div className="flex justify-between items-end">
            <div>
              <h2 className="text-3xl font-serif font-bold text-stone-900 dark:text-stone-100">Botany Report</h2>
              <p className="text-stone-500 dark:text-stone-400 font-medium">Results generated by Leafy AI Engine</p>
            </div>
            <button 
              onClick={() => { setCurrentPlant(null); setLastImage(null); }}
              className="group px-6 py-3 bg-white dark:bg-stone-900 border border-stone-200 dark:border-stone-800 rounded-2xl text-emerald-600 dark:text-emerald-400 hover:text-emerald-700 dark:hover:text-emerald-300 font-bold flex items-center gap-2 shadow-sm transition-all hover:shadow-md"
            >
              Analyze New
            </button>
          </div>
          <PlantCard 
            plant={currentPlant} 
            image={lastImage || undefined}
            onClose={() => setCurrentPlant(null)} 
            onSetReminder={onSetReminder}
            activeReminders={reminders.filter(r => r.plantId === currentPlant.id)}
          />
        </div>
      )}

      {!currentPlant && !isLoading && history.length > 0 && (
        <section className="space-y-8 animate-in fade-in duration-1000 delay-300">
          <div className="flex justify-between items-end">
            <div>
              <h2 className="text-2xl font-serif font-bold text-stone-900 dark:text-stone-100">Recent Discoveries</h2>
              <p className="text-stone-500 dark:text-stone-400 text-sm">Your latest botanical encounters</p>
            </div>
            <Link to="/history" className="text-emerald-600 dark:text-emerald-400 hover:underline text-sm font-black uppercase tracking-widest">See Full Journal</Link>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-6">
            {history.slice(0, 4).map((item) => (
              <div 
                key={item.id} 
                className="group cursor-pointer space-y-4"
                onClick={() => { setCurrentPlant(item); setLastImage(item.imageUrl || null); }}
              >
                <div className="aspect-[4/5] rounded-[2rem] overflow-hidden bg-white dark:bg-stone-900 shadow-sm border border-stone-100 dark:border-stone-800 group-hover:shadow-xl group-hover:shadow-emerald-500/10 transition-all duration-500">
                  {item.imageUrl ? (
                    <img src={item.imageUrl} alt={item.commonName} className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700" />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center text-stone-200 dark:text-stone-700"><TreePine size={48} /></div>
                  )}
                </div>
                <div>
                  <h3 className="font-bold text-stone-900 dark:text-stone-100 text-base group-hover:text-emerald-700 dark:group-hover:text-emerald-400 transition-colors truncate">{item.commonName}</h3>
                  <p className="text-stone-400 dark:text-stone-500 text-xs font-bold uppercase tracking-widest truncate">{item.scientificName}</p>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}
    </div>
  );
};

export default Home;
